repository:
  default_branch: main
branches:
  - name: main
    protection:
      enforce_admins: true
      required_status_checks:
        strict: true
        contexts:
          - 'Build & Deploy / build'
          - 'OSSAR / OSSAR-Scan'
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
