# .github/workflows/content-correction.yml
name: Content Correction

on:
  workflow_dispatch:
    inputs:
      src:
        description: 'File path to move'
        required: true
        type: string
      dest:
        description: 'Destination directory under content/'
        required: true
        type: string

permissions:
  contents: write

jobs:
  correct:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> $GITHUB_OUTPUT
            echo "command=install --frozen-lockfile" >> $GITHUB_OUTPUT
            echo "runner=pnpm" >> $GITHUB_OUTPUT
            echo "lockfile=pnpm-lock.yaml" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager" && exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ${{ steps.detect-package-manager.outputs.manager }}
          cache-dependency-path: ./${{ steps.detect-package-manager.outputs.lockfile }}

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Move file
        run: |
          dest_dir="content/${{ github.event.inputs.dest }}"
          mkdir -p "$dest_dir"
          git mv "${{ github.event.inputs.src }}" "$dest_dir/"

      - name: Run build scripts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BASE_URL: 'https://adrianwedd.github.io'
        run: |
          dest_dir="content/${{ github.event.inputs.dest }}"
          moved_file="$dest_dir/$(basename '${{ github.event.inputs.src }}')"
          node scripts/build-insights.mjs "$moved_file"
          node scripts/build-search-index.mjs
          node scripts/build-rss.mjs

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit -am "chore: correct content via workflow"
            git push
          fi
