name: Build & Deploy
# Deploy static site to the `gh-pages` branch

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Security Audit
        run: npm audit --audit-level=high
      - run: npm run lint
      - run: npm test
      - run: node scripts/fetch-gh-repos.mjs
      - run: node scripts/classify-inbox.mjs
      - run: node scripts/build-insights.mjs
      - run: node scripts/agent-bus.mjs
      - run: npm run build
      - run: node scripts/build-rss.mjs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
      - name: Slack Notify
        uses: 8398a7/action-slack@v3
        if: failure()
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
